python_tests(
    extra_env_vars=[
        "CALENDAR_URL=https://raw.githubusercontent.com/collective/icalendar/v5.0.11/src/icalendar/tests/calendars/timezone_rdate.ics",
        "ENCRYPTION_KEY=foobar=",
    ],
)
