---
name: Trigger CalChecker
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: 0 22 * * *  # Every day at 22:00 UTC

jobs:
  build:
    name: Trigger CalChecker run
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up pants
        uses: pantsbuild/actions/init-pants@v9
        with:
          gha-cache-key: ${{ runner.os }}-pants-init-${{ hashFiles('pants.toml') }}
          named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
      - name: Download state artifact
        id: download-state
        uses: dawidd6/action-download-artifact@v6
        with:
          name: calendar-state
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
        continue-on-error: true
      - name: CalChecker run
        id: calchecker-run
        run: |
          LOGS=$(pants run calchecker:main)
          # Mask each line of the output to hide it in logs
          while read -r line; do
            if [ -n "$line" ]; then
              echo "::add-mask::${line}"
            fi
          done <<< "$LOGS"

          echo "LOGS<<EOF" >> "$GITHUB_OUTPUT"
          echo "$LOGS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
      - name: Upload state artifact
        if: steps.calchecker-run.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: calendar-state
          path: calendar.bin
          if-no-files-found: error
          overwrite: true
      - name: Send mail on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            CalChecker failed
          body: >
            Job '${{ github.job }}' in worflow ${{ github.workflow }} of ${{ github.repository }} finished in a
            ${{ job.status }} state.

            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: CalChecker
      - name: Send mail
        if: steps.calchecker-run.outputs.LOGS != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            New changes from CalChecker
          body: >
            ${{ steps.calchecker-run.outputs.LOGS }}
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: CalChecker
